In [4]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import random

Clase y funciones para abrir el archivo, guardar la inrformacion de las imagenes y sus clases, y aleatorizarlos.

In [5]:
def shuffle_lists(lst, lst2):
    n = len(lst2)
    for i in range(n - 1, 0, -1):
        j = random.randint(0, i)
        lst[i], lst[j] = np.copy(lst[j]), np.copy(lst[i])
        lst2[i], lst2[j] = lst2[j], lst2[i]
    return lst, lst2

def shuffle(data, target):
    # Hacer un shuffle de las listas
    dataRand, targetRand = shuffle_lists(data, target)
    return dataRand, targetRand

In [6]:
# Leer el archivo de texto
class Data:
    def __init__(self):
        self._data = None
        self._target = None
        self._randomData = None
        self._randomTarget = None
        
    # Metodos getters
    def getRandomData(self):
        return self._randomData
    
    def getRandomTarget(self):
        return self._randomTarget
    
    # Funcion para leer el archivo y guardar las imagenes y sus clases
    def load_data(self):
        with open("optdigits.tes", "r") as datos:
            valores = []
            for linea in datos:
                valores.append([x for x in linea.strip().split(",")])
                
            # Crear matriz para guardar los valores de data
            data = np.zeros((len(valores), 64))
            for i in range(len(valores)):
                data[i] = valores[i][:64]
                
            self._data = np.copy(data)
            
            # Crear matriz para guardar los valores de target (clases)
            target = np.zeros((len(valores)))
            for i in range(len(valores)):
                target[i] = valores[i][64]
                
            self._target = np.copy(target)
            
            
        print("Se cargaron los datos")
    
    # Funcion para aleatorizar la informacion guardada
    def randomizer(self):
        # Crear matriz auxiliar para permutar filas de la matriz de datos
        numDatos, numChar = self._data.shape
        
        randomData = np.copy(self._data)
        # Crear arreglo auxiliar para permutar clases
        numTarget = self._target.shape
        
        randomTarget = np.copy(self._target)
        
        # Tomar un valor random desde 0 hasta numDatos y mezclar
        a, b = shuffle(randomData, randomTarget)
        
        # Guardar la matriz con filas intercambiadas y el arreglo con datos intercambiados
        self._randomData = np.copy(a)
        self._randomTarget = np.copy(b)
        print("Datos aleatorizados")

Cargar el archivo y hacer aleatorios los datos con los que se va a trabajar

In [7]:
data = Data()
data.load_data()
data.randomizer()

FileNotFoundError: [Errno 2] No such file or directory: 'optdigits.tes'

In [ ]:
# Devuelve los imagenes aleatorias con las que se va a trabajar
datos = data.getRandomData()
datos[:2]

array([[ 0.,  0., 13., 13.,  8.,  2.,  0.,  0.,  0.,  5., 16., 16., 16.,
        12.,  0.,  0.,  0.,  1., 15., 12.,  0.,  0.,  0.,  0.,  0.,  0.,
        12., 13.,  7.,  1.,  0.,  0.,  0.,  0.,  8., 16., 16., 12.,  0.,
         0.,  0.,  0.,  0.,  4.,  9., 16.,  3.,  0.,  0.,  0.,  1.,  5.,
        14., 15.,  1.,  0.,  0.,  0., 10., 16., 16.,  6.,  0.,  0.],
       [ 0.,  0.,  1., 11., 16., 16.,  8.,  0.,  0.,  0.,  5., 11.,  9.,
        16., 11.,  0.,  0.,  0.,  0.,  0.,  2., 16.,  6.,  0.,  0.,  0.,
         6.,  9., 12., 16.,  9.,  0.,  0.,  1., 16., 16., 16., 14.,  3.,
         0.,  0.,  0.,  3.,  5., 16.,  7.,  0.,  0.,  0.,  0.,  0.,  8.,
        14.,  0.,  0.,  0.,  0.,  0.,  1., 16.,  5.,  0.,  0.,  0.]])

In [ ]:
# Devuelve las clases de las imagenes aleatorizadas
target = data.getRandomTarget()
target

array([5., 7., 7., ..., 9., 8., 5.])

Se muestra un ejemplo de imagen aleatoria y su clase correspondiente

In [ ]:
# Ejemplo
#num = random.randint(0, 1700)
datos_res = np.reshape(datos[0], (8,8))
print(f"Numero{target[0]}")
plt.imshow(datos_res, cmap=plt.cm.gray_r, interpolation="nearest")

NameError: name 'np' is not defined

In [ ]:
# Dataframe para visualizar los datos
df = pd.DataFrame(datos)
df["target"] = target
df.head(10)

0    1     2     3     4     5    6    7    8     9  ...   55   56   57  \
0  0.0  0.0  13.0  13.0   8.0   2.0  0.0  0.0  0.0   5.0  ...  0.0  0.0  0.0   
1  0.0  0.0   1.0  11.0  16.0  16.0  8.0  0.0  0.0   0.0  ...  0.0  0.0  0.0   
2  0.0  0.0   5.0  11.0  16.0  16.0  5.0  0.0  0.0   3.0  ...  0.0  0.0  0.0   
3  0.0  0.0   9.0  16.0  16.0   7.0  0.0  0.0  0.0  13.0  ...  0.0  0.0  0.0   
4  0.0  0.0   0.0   8.0  12.0   0.0  0.0  0.0  0.0   0.0  ...  0.0  0.0  0.0   
5  0.0  1.0   7.0  13.0  16.0  11.0  0.0  0.0  0.0  11.0  ...  0.0  0.0  0.0   
6  0.0  0.0   0.0   8.0  16.0   0.0  0.0  0.0  0.0   0.0  ...  0.0  0.0  0.0   
7  0.0  0.0   2.0   9.0  14.0  12.0  0.0  0.0  0.0   0.0  ...  0.0  0.0  0.0   
8  0.0  0.0   9.0  16.0  16.0   8.0  0.0  0.0  0.0   5.0  ...  0.0  0.0  0.0   
9  0.0  0.0   4.0  14.0  16.0  15.0  1.0  0.0  0.0   5.0  ...  0.0  0.0  0.0   

     58    59    60    61   62   63  target  
0  10.0  16.0  16.0   6.0  0.0  0.0     5.0  
1   1.0  16.0   5.0   0.0  0.0  0.0     7.0  
2   8.0  16.0   0.0   0.0  0.0  0.0     7.0  
3   9.0  16.0  16.0  14.0  5.0  0.0     3.0  
4   0.0  12.0  10.0   0.0  0.0  0.0     4.0  
5   7.0  16.0  12.0   7.0  0.0  0.0     3.0  
6   0.0  11.0  13.0   0.0  0.0  0.0     4.0  
7   1.0  12.0  16.0   8.0  0.0  0.0     0.0  
8   9.0  16.0  15.0   5.0  0.0  0.0     2.0  
9   3.0  16.0   2.0   0.0  0.0  0.0     9.0  

[10 rows x 65 columns]

In [ ]:
# Se separan los datos de prueba (500) y los datos de entrenamiento (1000)
df_train, df_test = df[:1000], df[1000:1500]

# Se preparan los datos de train y los datos de test
X_train = df_train.drop(columns=["target"]).values
y_train = df_train["target"].values

X_test = df_test.drop(columns=["target"]).values
y_test = df_test["target"].values

In [ ]:
# Funcion para calcular la distancia euclideana
def euc_dist(x1, x2):
    return np.sqrt(np.sum((x1-x2)**2))

Se crea la clase del modelo de KNN

In [ ]:
class knnAlgorithm:
    def __init__(self, k):
        self.k = k
        
    def fit(self, X, y):
        self.X_train = X # Imagenes
        self.y_train = y # Clases
        
    def predict(self, X):
        print("Preparando predicciones")
        y_pred = []
        
        # Obtener la distancia a todos los puntos
        for i in range(len(X)):
            distances = np.array([euc_dist(X[i], x_t) for x_t in self.X_train])
            
            # Ordenar las distancias y devolver solo los primeros k vecinos
            sort_distance = np.argsort(distances)[: self.k]

            # Guardar las distancias en un arreglo
            knn = self.y_train[sort_distance]

            # Contar las clases más coumnes
            label, counts = np.unique(knn, return_counts = True)

            y_pred.append(label[np.argmax(counts)])
        return np.array(y_pred)
    
    def des(self, X):
        print("Preparando predicciones...")
        y_pred = [self.predict(x) for x in X]
        return np.array(y_pred)

Se inicializa el modelo para k=3 y se entrena con los datos de X_train y y_train

In [ ]:
model = knnAlgorithm(k=3)
model.fit(X_train, y_train)

Se comprueba la precisión del modelo con los mismos datos de entrenamiento

In [ ]:
y_pred = model.predict(X_train)
y_pred[:10]

Preparando predicciones


array([5., 7., 7., 3., 4., 3., 4., 0., 2., 9.])

In [ ]:
y_train[:10]

array([5., 7., 7., 3., 4., 3., 4., 0., 2., 9.])

In [ ]:
mask = y_pred == y_train
mask[:10]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

La precision del modelo fue:

In [ ]:
model_accuracy = np.mean(y_pred == y_train)
print(f"Precisión del modelo: {model_accuracy * 100:.2f}%")

Precisión del modelo: 99.00%


# Prueba con datos de test

In [ ]:
y_pred = model.predict(X_test)
y_pred[:100]

Preparando predicciones


array([5., 6., 7., 4., 4., 9., 5., 7., 2., 8., 1., 2., 4., 6., 9., 9., 3.,
       0., 6., 6., 1., 0., 3., 6., 6., 1., 0., 3., 1., 7., 6., 5., 5., 2.,
       1., 2., 5., 5., 0., 8., 1., 6., 7., 1., 7., 0., 4., 3., 8., 0., 5.,
       1., 2., 7., 4., 8., 6., 6., 9., 9., 2., 7., 1., 2., 3., 3., 7., 7.,
       5., 7., 5., 9., 9., 4., 9., 6., 6., 6., 5., 0., 0., 9., 3., 5., 6.,
       0., 3., 4., 0., 5., 0., 2., 8., 8., 8., 8., 3., 4., 0., 7.])

In [ ]:
y_test[:100]

array([5., 6., 7., 4., 4., 9., 5., 7., 2., 8., 1., 2., 4., 6., 9., 9., 3.,
       0., 6., 6., 1., 0., 3., 6., 6., 1., 0., 3., 1., 7., 6., 5., 5., 2.,
       1., 2., 5., 5., 0., 8., 1., 6., 7., 1., 7., 0., 4., 3., 8., 0., 5.,
       1., 2., 7., 4., 8., 6., 6., 9., 9., 2., 7., 1., 2., 3., 3., 7., 7.,
       5., 4., 5., 9., 9., 4., 9., 6., 6., 6., 5., 0., 0., 9., 3., 5., 6.,
       0., 3., 4., 0., 5., 0., 2., 8., 8., 8., 8., 3., 4., 0., 7.])

In [ ]:
mask = y_pred == y_test
mask[:100]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

La precision del modelo para los datos de test fue:

In [ ]:
model_accuracy = np.mean(y_pred == y_test)
print(f"Model accuracy: {model_accuracy * 100:.2f}%")

Model accuracy: 98.80%
